#!/usr/bin/env python3
"""
Daily VZY Report Email Sender

Fetches latest Jira data (open bugs + tasks) and sends a formatted HTML email
to senior management. Designed to run via GitHub Actions on a daily cron schedule.

Required environment variables:
  JIRA_DOMAIN, JIRA_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY
  SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD
  REPORT_RECIPIENTS (comma-separated email addresses)

Optional:
  KPI_DATA_PATH - path to kpi_data.json (generated by kpi_collector.py)
"""

import os
import json
import boto3
from botocore.exceptions import ClientError
from datetime import datetime, timedelta, timezone
from requests.auth import HTTPBasicAuth
import requests

# ── Jira Config ──
JIRA_DOMAIN = os.environ.get('JIRA_DOMAIN', 'hbeindia.atlassian.net')
JIRA_EMAIL = os.environ.get('JIRA_EMAIL', '')
JIRA_API_TOKEN = os.environ.get('JIRA_API_TOKEN', '')
PROJECT_KEY = os.environ.get('JIRA_PROJECT_KEY', 'VF')

# ── AWS SES Email Config ──
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_REGION = os.environ.get('AWS_REGION', 'ap-south-1')
SES_SENDER_EMAIL = os.environ.get('SES_SENDER_EMAIL', 'watcho1tech@dishd2h.com')
REPORT_RECIPIENTS = os.environ.get('REPORT_RECIPIENTS', '').split(',')

# ── Platforms & Statuses ──
PLATFORMS = ['ANDROID', 'ATV', 'CMS Adaptor', 'CMS Dashboard', 'DishIT', 'IOS', 'LG_TV', 'SAM_TV', 'WEB']
OPEN_STATUSES = ['Open', 'In Progress', 'Reopened', 'In Review', 'Issue Accepted']

# ── KPI Config ──
KPI_DATA_PATH = os.environ.get('KPI_DATA_PATH', os.path.join(os.path.dirname(os.path.abspath(__file__)), 'kpi_data.json'))


def fetch_open_issues(issue_type):
    """Fetch open bugs or tasks from Jira."""
    auth = HTTPBasicAuth(JIRA_EMAIL, JIRA_API_TOKEN)
    headers = {'Accept': 'application/json', 'Content-Type': 'application/json'}

    status_clause = ', '.join(f'"{s}"' for s in OPEN_STATUSES)
    jql = f'project = {PROJECT_KEY} AND issuetype = "{issue_type}" AND status IN ({status_clause}) ORDER BY priority DESC, updated DESC'
    url = f'https://{JIRA_DOMAIN}/rest/api/3/search/jql'

    all_issues = []
    next_page_token = None

    while True:
        payload = {
            'jql': jql,
            'maxResults': 100,
            'fields': ['summary', 'status', 'priority', 'assignee', 'labels', 'components', 'created', 'updated', 'issuetype']
        }
        if next_page_token:
            payload['nextPageToken'] = next_page_token

        response = requests.post(url, headers=headers, auth=auth, json=payload)
        response.raise_for_status()
        data = response.json()

        issues = data.get('issues', [])
        all_issues.extend(issues)

        next_page_token = data.get('nextPageToken')
        if not next_page_token or len(issues) == 0:
            break

    return all_issues


def detect_platform(issue):
    """Detect platform from issue fields."""
    fields = issue.get('fields', {})
    labels = [l.upper() for l in fields.get('labels', [])]
    components = [c.get('name', '').upper() for c in fields.get('components', [])]
    summary = (fields.get('summary') or '').upper()
    all_text = ' '.join(labels + components + [summary])

    platform_patterns = {
        'CMS Adaptor': ['CMS ADAPTOR', 'CMS_ADAPTOR'],
        'CMS Dashboard': ['CMS DASHBOARD', 'CMS_DASHBOARD'],
        'DishIT': ['DISHIT', 'DISH IT'],
        'LG_TV': ['LG_TV', 'LGTV', 'LG TV', 'WEBOS'],
        'SAM_TV': ['SAM_TV', 'SAMTV', 'SAM TV', 'SAMSUNG TV', 'TIZEN'],
        'ATV': ['ATV', 'ANDROID TV', 'FIRE TV', 'FIRETV'],
        'ANDROID': ['ANDROID'],
        'IOS': ['IOS', 'APPLE', 'IPHONE', 'IPAD'],
        'WEB': ['WEB'],
    }

    for platform, patterns in platform_patterns.items():
        for pattern in patterns:
            if pattern in all_text:
                return platform
    return 'Other'


def summarize_issues(issues):
    """Build platform-wise and status-wise summary."""
    platform_summary = {}
    status_summary = {}
    priority_summary = {}

    for issue in issues:
        fields = issue.get('fields', {})
        status = fields.get('status', {}).get('name', 'Unknown')
        priority = fields.get('priority', {}).get('name', 'None') if fields.get('priority') else 'None'
        platform = detect_platform(issue)

        platform_summary[platform] = platform_summary.get(platform, 0) + 1
        status_summary[status] = status_summary.get(status, 0) + 1
        priority_summary[priority] = priority_summary.get(priority, 0) + 1

    return {
        'total': len(issues),
        'by_platform': dict(sorted(platform_summary.items(), key=lambda x: -x[1])),
        'by_status': dict(sorted(status_summary.items(), key=lambda x: -x[1])),
        'by_priority': dict(sorted(priority_summary.items(), key=lambda x: -x[1])),
    }


def load_kpi_data():
    """Load KPI data from kpi_data.json if available."""
    if os.path.exists(KPI_DATA_PATH):
        with open(KPI_DATA_PATH, 'r') as f:
            return json.load(f)
    return None


def build_html_report(bug_summary, task_summary, kpi_data=None):
    """Build the HTML email body."""
    report_date = (datetime.now(timezone.utc) - timedelta(hours=5, minutes=30)).strftime('%d %B %Y')  # IST approx
    now_ist = (datetime.now(timezone.utc) + timedelta(hours=5, minutes=30)).strftime('%I:%M %p IST')

    def make_table(summary, label):
        rows = ''
        # Platform breakdown
        for platform, count in summary['by_platform'].items():
            rows += f'<tr><td style="padding:8px 14px;border-bottom:1px solid #e5e7eb;">{platform}</td><td style="padding:8px 14px;border-bottom:1px solid #e5e7eb;text-align:center;font-weight:700;">{count}</td></tr>'
        rows += f'<tr style="background:#f0f9ff;font-weight:700;"><td style="padding:10px 14px;">TOTAL</td><td style="padding:10px 14px;text-align:center;color:#1e40af;">{summary["total"]}</td></tr>'

        status_chips = ''
        for status, count in summary['by_status'].items():
            color = {'Open': '#ef4444', 'In Progress': '#f59e0b', 'Reopened': '#f97316', 'In Review': '#8b5cf6', 'Issue Accepted': '#10b981'}.get(status, '#64748b')
            status_chips += f'<span style="display:inline-block;padding:4px 12px;margin:3px;border-radius:20px;background:{color}22;color:{color};font-size:13px;font-weight:600;">{status}: {count}</span>'

        priority_chips = ''
        for priority, count in summary['by_priority'].items():
            priority_chips += f'<span style="display:inline-block;padding:4px 10px;margin:3px;border-radius:12px;background:#f1f5f9;color:#334155;font-size:12px;">{priority}: {count}</span>'

        return f'''
        <div style="margin-bottom:30px;">
            <h2 style="color:#1e293b;font-size:18px;margin-bottom:4px;">Open {label} Summary</h2>
            <p style="color:#64748b;font-size:13px;margin-bottom:12px;">Total open {label.lower()}: <b style="color:#1e40af;font-size:16px;">{summary["total"]}</b></p>
            <div style="margin-bottom:12px;">{status_chips}</div>
            <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;">
                <thead><tr style="background:#1e293b;">
                    <th style="padding:10px 14px;text-align:left;color:#f8fafc;font-size:13px;">Platform</th>
                    <th style="padding:10px 14px;text-align:center;color:#f8fafc;font-size:13px;">Count</th>
                </tr></thead>
                <tbody>{rows}</tbody>
            </table>
            <div style="margin-top:8px;">{priority_chips}</div>
        </div>'''

    bug_section = make_table(bug_summary, 'Bugs')
    task_section = make_table(task_summary, 'Tasks')

    # KPI Section
    kpi_section = ''
    if kpi_data:
        kpi_section = '<div style="margin-bottom:30px;">'
        kpi_section += '<h2 style="color:#1e293b;font-size:18px;margin-bottom:12px;">App & Web KPI Matrix</h2>'

        if kpi_data.get('apps'):
            kpi_section += '<h3 style="color:#475569;font-size:14px;margin-bottom:8px;">App Performance</h3>'
            kpi_section += '<table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;margin-bottom:16px;">'
            kpi_section += '<thead><tr style="background:#1e293b;"><th style="padding:8px 12px;color:#f8fafc;text-align:left;font-size:12px;">App</th><th style="padding:8px 12px;color:#f8fafc;text-align:center;font-size:12px;">DAU</th><th style="padding:8px 12px;color:#f8fafc;text-align:center;font-size:12px;">Crash Rate</th><th style="padding:8px 12px;color:#f8fafc;text-align:center;font-size:12px;">ANR Rate</th><th style="padding:8px 12px;color:#f8fafc;text-align:center;font-size:12px;">Rating</th></tr></thead><tbody>'
            for app_name, metrics in kpi_data['apps'].items():
                kpi_section += f'<tr><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:600;">{app_name}</td>'
                kpi_section += f'<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{metrics.get("dau", "N/A")}</td>'
                kpi_section += f'<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{metrics.get("crash_rate", "N/A")}</td>'
                kpi_section += f'<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{metrics.get("anr_rate", "N/A")}</td>'
                kpi_section += f'<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{metrics.get("rating", "N/A")}</td></tr>'
            kpi_section += '</tbody></table>'

        if kpi_data.get('web'):
            kpi_section += '<h3 style="color:#475569;font-size:14px;margin-bottom:8px;">Web/mWeb Performance</h3>'
            kpi_section += '<table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;margin-bottom:16px;">'
            kpi_section += '<thead><tr style="background:#1e293b;"><th style="padding:8px 12px;color:#f8fafc;text-align:left;font-size:12px;">Property</th><th style="padding:8px 12px;color:#f8fafc;text-align:center;font-size:12px;">LCP</th><th style="padding:8px 12px;color:#f8fafc;text-align:center;font-size:12px;">FID</th><th style="padding:8px 12px;color:#f8fafc;text-align:center;font-size:12px;">CLS</th><th style="padding:8px 12px;color:#f8fafc;text-align:center;font-size:12px;">Page Load</th></tr></thead><tbody>'
            for prop_name, metrics in kpi_data['web'].items():
                kpi_section += f'<tr><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:600;">{prop_name}</td>'
                kpi_section += f'<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{metrics.get("lcp", "N/A")}</td>'
                kpi_section += f'<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{metrics.get("fid", "N/A")}</td>'
                kpi_section += f'<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{metrics.get("cls", "N/A")}</td>'
                kpi_section += f'<td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{metrics.get("page_load", "N/A")}</td></tr>'
            kpi_section += '</tbody></table>'

        kpi_section += f'<p style="color:#94a3b8;font-size:11px;">KPI data last updated: {kpi_data.get("updated_at", "N/A")}</p>'
        kpi_section += '</div>'
    else:
        kpi_section = '''
        <div style="margin-bottom:30px;padding:20px;background:#fffbeb;border:1px solid #fde68a;border-radius:8px;">
            <h3 style="color:#92400e;font-size:14px;margin-bottom:4px;">KPI Data Not Available</h3>
            <p style="color:#a16207;font-size:13px;">App & Web performance KPI data will appear here once Firebase credentials are configured and kpi_collector.py generates kpi_data.json.</p>
        </div>'''

    html = f'''<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:700px;margin:0 auto;padding:20px;background:#f8fafc;">
    <div style="background:linear-gradient(135deg,#1e3a5f,#0f172a);padding:24px;border-radius:12px 12px 0 0;">
        <h1 style="color:#f8fafc;font-size:22px;margin:0;">Daily VZY Report</h1>
        <p style="color:#94a3b8;font-size:13px;margin:4px 0 0;">{report_date} | Generated at {now_ist}</p>
    </div>
    <div style="background:#ffffff;padding:24px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px;">
        {bug_section}
        <hr style="border:none;border-top:1px solid #e5e7eb;margin:24px 0;">
        {task_section}
        <hr style="border:none;border-top:1px solid #e5e7eb;margin:24px 0;">
        {kpi_section}
        <div style="margin-top:24px;padding:16px;background:#f1f5f9;border-radius:8px;text-align:center;">
            <p style="color:#475569;font-size:12px;margin:0;">
                <a href="https://sunilk9898.github.io/vf-bug-dashboard-chatbot/" style="color:#2563eb;">View Full Dashboard</a> |
                <a href="https://hbeindia.atlassian.net/jira/software/projects/VZY/board" style="color:#2563eb;">Open Jira Board</a>
            </p>
            <p style="color:#94a3b8;font-size:11px;margin:8px 0 0;">This is an automated report from VZY Bug Health Dashboard</p>
        </div>
    </div>
</body>
</html>'''
    return html


def get_ses_client():
    """Get AWS SES client."""
    if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
        return boto3.client(
            'ses',
            region_name=AWS_REGION,
            aws_access_key_id=AWS_ACCESS_KEY_ID,
            aws_secret_access_key=AWS_SECRET_ACCESS_KEY
        )
    return boto3.client('ses', region_name=AWS_REGION)


def send_email(subject, html_body):
    """Send HTML email via AWS SES."""
    if not AWS_ACCESS_KEY_ID or not AWS_SECRET_ACCESS_KEY:
        print("WARNING: AWS credentials not configured. Saving report to file instead.")
        report_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'daily_report.html')
        with open(report_path, 'w') as f:
            f.write(html_body)
        print(f"Report saved to {report_path}")
        return False

    recipients = [r.strip() for r in REPORT_RECIPIENTS if r.strip()]
    if not recipients:
        print("WARNING: No recipients configured. Saving report to file instead.")
        report_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'daily_report.html')
        with open(report_path, 'w') as f:
            f.write(html_body)
        print(f"Report saved to {report_path}")
        return False

    # Also save report to file for reference
    report_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'daily_report.html')
    with open(report_path, 'w') as f:
        f.write(html_body)

    try:
        client = get_ses_client()
        response = client.send_email(
            Source=SES_SENDER_EMAIL,
            Destination={'ToAddresses': recipients},
            Message={
                'Subject': {'Data': subject, 'Charset': 'UTF-8'},
                'Body': {
                    'Html': {'Data': html_body, 'Charset': 'UTF-8'}
                }
            }
        )
        print(f"Email sent via AWS SES to {len(recipients)} recipients: {', '.join(recipients)}")
        print(f"  Message ID: {response['MessageId']}")
        return True
    except ClientError as e:
        print(f"ERROR: AWS SES failed: {e.response['Error']['Message']}")
        print(f"Report saved to {report_path}")
        return False


def main():
    if not JIRA_EMAIL or not JIRA_API_TOKEN:
        print("ERROR: JIRA_EMAIL and JIRA_API_TOKEN environment variables required.")
        exit(1)

    print("Fetching open bugs...")
    bugs = fetch_open_issues('Bug')
    bug_summary = summarize_issues(bugs)
    print(f"  Found {bug_summary['total']} open bugs")

    print("Fetching open tasks...")
    tasks = fetch_open_issues('Task')
    task_summary = summarize_issues(tasks)
    print(f"  Found {task_summary['total']} open tasks")

    # Load KPI data if available
    kpi_data = load_kpi_data()
    if kpi_data:
        print(f"  KPI data loaded (updated: {kpi_data.get('updated_at', 'unknown')})")
    else:
        print("  KPI data not available (kpi_data.json not found)")

    # Build report
    report_date = (datetime.now(timezone.utc) + timedelta(hours=5, minutes=30)).strftime('%d %b %Y')
    subject = f"Daily VZY Report - {report_date} | Bugs: {bug_summary['total']} | Tasks: {task_summary['total']}"
    html_body = build_html_report(bug_summary, task_summary, kpi_data)

    # Send or save
    send_email(subject, html_body)

    # Also save summary as JSON for reference
    summary = {
        'report_date': report_date,
        'generated_at': datetime.now(timezone.utc).isoformat() + 'Z',
        'bugs': bug_summary,
        'tasks': task_summary,
        'kpi_available': kpi_data is not None,
    }
    summary_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'daily_report_summary.json')
    with open(summary_path, 'w') as f:
        json.dump(summary, f, indent=2)
    print(f"Summary saved to {summary_path}")


if __name__ == '__main__':
    main()
